/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.login.view;

import br.com.ifba.usuario.validar.ValidadorUsuario;
import javax.swing.JOptionPane;

/**
 *
 * @author mariorocha
 */
public class MainCadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainCadastro.class.getName());

    /**
     * Creates new form MainCadastro
     */
    public MainCadastro() {
        initComponents();
        // Janela fica no centro da tela
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputNome = new javax.swing.JTextField();
        labelForInputNome = new javax.swing.JLabel();
        labelForInputCPF = new javax.swing.JLabel();
        inputCPF = new javax.swing.JTextField();
        escolhaGenero = new javax.swing.JComboBox<>();
        labelForEscolhaGenero = new javax.swing.JLabel();
        labelForInputDataDeNascimento = new javax.swing.JLabel();
        inputDataDeNascimento = new javax.swing.JTextField();
        labelForInputTelefone = new javax.swing.JLabel();
        inputTelefone = new javax.swing.JTextField();
        labelForInputEmail = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        labelForInputLogin = new javax.swing.JLabel();
        inputLogin = new javax.swing.JTextField();
        labelForInputSenha = new javax.swing.JLabel();
        inputSenha = new javax.swing.JTextField();
        inputRepetirSenha = new javax.swing.JTextField();
        labelForInputRepetirSenha = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelForInputNome.setText("Nome Completo");

        labelForInputCPF.setText("CPF");

        escolhaGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));

        labelForEscolhaGenero.setText("Genêro");

        labelForInputDataDeNascimento.setText("Data de Nascimento");

        labelForInputTelefone.setText("Telefone");

        labelForInputEmail.setText("Email");

        labelForInputLogin.setText("Login");

        labelForInputSenha.setText("Senha");

        labelForInputRepetirSenha.setText("Repetir Senha");

        btnCadastrar.setBackground(new java.awt.Color(0, 102, 255));
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(this::btnCadastrarActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(labelForEscolhaGenero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelForInputDataDeNascimento)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(labelForInputNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(labelForInputCPF))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(inputNome)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(escolhaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(inputDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(inputTelefone)
                            .addComponent(inputEmail)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelForInputTelefone)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelForInputEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelForInputLogin))))
                            .addComponent(inputLogin)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputSenha)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addComponent(labelForInputSenha))
                                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputRepetirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelForInputRepetirSenha)
                                        .addGap(28, 28, 28))
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(labelForInputNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputNome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelForInputCPF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelForEscolhaGenero)
                    .addComponent(labelForInputDataDeNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(escolhaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputDataDeNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelForInputTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelForInputEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelForInputLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelForInputSenha)
                            .addComponent(labelForInputRepetirSenha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inputRepetirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        MainLogin retornarTelaLogin = new MainLogin();
        retornarTelaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // Capturo os dados dos inputs da tela de cadastro
        String nome = inputNome.getText();
        String cpf = inputCPF.getText();
        String genero = (String) escolhaGenero.getSelectedItem();
        String dataDeNascimento = inputDataDeNascimento.getText();
        String telefone = inputTelefone.getText();
        String email = inputEmail.getText();
        String login = inputLogin.getText();
        String senha = inputSenha.getText();
        String confirmacaoDeSenha = inputRepetirSenha.getText();
        // Testa se um dos campos esta vazio
        if(nome.isEmpty()
                || cpf.isEmpty()
                || dataDeNascimento.isEmpty()
                || telefone.isEmpty()
                || email.isEmpty()
                || login.isEmpty()
                || senha.isEmpty()
                || confirmacaoDeSenha.isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha Todos os Campos!!", "Campos incompletos", JOptionPane.ERROR_MESSAGE);
        }else{
            // Testa se existe a palavra proíbida
            if(ValidadorUsuario.contemPalavraProibida(nome)
                    || ValidadorUsuario.contemPalavraProibida(cpf)
                    || ValidadorUsuario.contemPalavraProibida(dataDeNascimento)
                    || ValidadorUsuario.contemPalavraProibida(telefone)
                    || ValidadorUsuario.contemPalavraProibida(email)
                    || ValidadorUsuario.contemPalavraProibida(login)
                    || ValidadorUsuario.contemPalavraProibida(senha)){
                        JOptionPane.showMessageDialog(null, "Você digitou uma palavra proíbida!!", "Palavras proíbidas", JOptionPane.ERROR_MESSAGE);
            }else{
                // Testa se as senhas são iguais
                if(!senha.equals(confirmacaoDeSenha)){
                    JOptionPane.showMessageDialog(null, "Verifique as senhas!!", "Senhas não coincidem", JOptionPane.ERROR_MESSAGE);
                }else{
                    //Caso sejam iguais, realiza o cadastro
                    JOptionPane.showMessageDialog(null, "Cadastro efetuado", "Confirmacao de cadastro", JOptionPane.INFORMATION_MESSAGE);
                }
            }  
        }
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainCadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> escolhaGenero;
    private javax.swing.JTextField inputCPF;
    private javax.swing.JTextField inputDataDeNascimento;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputLogin;
    private javax.swing.JTextField inputNome;
    private javax.swing.JTextField inputRepetirSenha;
    private javax.swing.JTextField inputSenha;
    private javax.swing.JTextField inputTelefone;
    private javax.swing.JLabel labelForEscolhaGenero;
    private javax.swing.JLabel labelForInputCPF;
    private javax.swing.JLabel labelForInputDataDeNascimento;
    private javax.swing.JLabel labelForInputEmail;
    private javax.swing.JLabel labelForInputLogin;
    private javax.swing.JLabel labelForInputNome;
    private javax.swing.JLabel labelForInputRepetirSenha;
    private javax.swing.JLabel labelForInputSenha;
    private javax.swing.JLabel labelForInputTelefone;
    // End of variables declaration//GEN-END:variables
}
